**Q1. What is difference between list and numpy array?**

	             	                      

* **Feature             Python List                      NumPy Array**

1. Library	      # Built into Python	              # Requires numpy library

2. Data types	    # Can contain different types	    # Usually same data type

3. Speed	        # Slower for numerical operations	# Faster for numerical ops

4. Memory	        # Uses more memory	              # More memory efficient

5. Maths ops   	  # Need loops	                    # Direct element-wise ops

6. Dimensions	    # Mainly 1D, nested lists for     # multi-dimensional arrays
                    multiple dimensions

7. Best for	      # General-purpose data	          # Numericalscientific
                                                       calculations



* **Example Python list and Numpy array**



In [ ]:
# Python List

lst = [1, 2, 3, 4]
result = [x * 2 for x in lst]
print(result)

[2, 4, 6, 8]


In [ ]:
# With a list
[1, 2, 3] * 2

[1, 2, 3, 1, 2, 3]

In [ ]:
# NumPy Array

import numpy as np
arr = np.array([1, 2, 3, 4])
result = arr * 2
print(result)

[2 4 6 8]


In [ ]:
# with NumPy

np.array([1, 2, 3]) * 2

array([2, 4, 6])


**Q2.  Create 1D, 2D and 3D arrays of 1's**

In [ ]:
import numpy as np

In [ ]:
oneDimn = np.ones(5,dtype=int)
oneDimn
#oneDimn.ndim

array([1, 1, 1, 1, 1])

In [ ]:
twoDim = np.ones((3,4),dtype=int)
twoDim
#twoDim.ndim

2

In [ ]:
threeDim = np.ones((4,2,2),dtype=int)
threeDim
#threeDim.ndim

3

**Q3. Create an array of constant number**

In [ ]:
# syntax : np.full(shape, fill_value)

In [ ]:
np.full((4),5)            # 1D

array([5, 5, 5, 5])

In [ ]:
np.full((4,3),5)          # 2D

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
np.full((4,2,2),3)        # 3D

array([[[3, 3],
        [3, 3]],

       [[3, 3],
        [3, 3]],

       [[3, 3],
        [3, 3]],

       [[3, 3],
        [3, 3]]])

**Q4. Create Identity Matrix/ Scalar matrix (row column same number)**

In [ ]:
# Using eye  - can change column number
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [ ]:
np.eye(4,dtype=bool)

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [ ]:
np.eye(4,dtype=int)

In [ ]:
# Using identity - can't change column number
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

# **Assignment - Numpy**
1. Create 4x4 array of all True values
2. Create 4x4 array of all False values
3. Create 4x4 array of Digonal elements as 1's and Non diagonal elements as 0's
4. Create 4x4 array of Digonal elements as True and Non diagonal elements as False
5. Create 4x4 array of Digonal elements as False and Non diagonal elements as True

In [2]:
import numpy as np

#Identity matrix = Scalar matrix = same row same column

1. Create 4x4 array of all True values

In [6]:
a = np.full((4,4),'True')   # using shape and fill value
a

array([['True', 'True', 'True', 'True'],
       ['True', 'True', 'True', 'True'],
       ['True', 'True', 'True', 'True'],
       ['True', 'True', 'True', 'True']], dtype='<U4')

In [5]:
# using ones as true
b = np.ones((4,4), dtype=bool)
b

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [13]:
z = np.full((4,4),'A')   # using shape and fill value can change value
z

array([['A', 'A', 'A', 'A'],
       ['A', 'A', 'A', 'A'],
       ['A', 'A', 'A', 'A'],
       ['A', 'A', 'A', 'A']], dtype='<U1')

2. Create 4x4 array of all False values

In [14]:
c = np.full((4,4),'False')   # using shape and fill value
c

array([['False', 'False', 'False', 'False'],
       ['False', 'False', 'False', 'False'],
       ['False', 'False', 'False', 'False'],
       ['False', 'False', 'False', 'False']], dtype='<U5')

In [15]:
# using zeros as false
d = np.zeros((4, 4), dtype=bool)
d

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

3. Create 4x4 array of Digonal elements as 1's and Non diagonal elements as 0's

In [16]:
# Using eye
e = np.eye(4,dtype=int)          # 4 consider as row and column as we need 4x4 matrix
                                 # and index = default 0

#e = np.eye(4,4,0,dtype=int)     # row,column,digonal index = default 0
e

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [17]:
# Using identity
f = np.identity(4,dtype=int)
f

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

4. Create 4x4 array of Digonal elements as True and Non diagonal elements as False

In [21]:
# Using eye
g = np.eye(4,dtype=bool)          # 4 consider as row and column and index =default 0
#g = np.eye(4,4,0,dtype=bool)     # row,column,digonal index =default 0
g

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [20]:
# Using identity
h = np.identity(4,dtype=bool)
h

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

5. Create 4x4 array of Digonal elements as False and Non diagonal elements as True

In [22]:
# Using eye
k = ~np.eye(4,dtype=bool)           # row and column =4 ,digonal index =default 0
#k = ~np.eye(4,4,0,dtype=bool)
k

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [26]:
# Using identity
l = ~np.identity(4,dtype=bool)
l

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [25]:
m = ~np.eye(5,dtype=bool)
m

array([[False,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True,  True,  True, False]])