**Q1. reshape() vs resize()**

              reshape()	                      resize()

1. Changes the shape of an array	    1. Changes the size & shape of an array
2. Does not change the original 	    2. Changes the original array when       array                                    used as arr.resize()
3. Total number of elements must 	    3. Number of elements can increase or
  remain the same                         decrease
4. Returns a new reshaped array	      4. Can modify the original array directly


* **Examples of reshape and resize**



In [35]:
import numpy as np

In [36]:
# reshape()

arr = np.arange(6)   # 1D array
#new_arr = arr.reshape(2, 3)   # 2D array

print("Reshape array 2D - ", arr.reshape(2, 3))  # after reshaping it only change temporary
print("Original array 1D - ", arr)


Reshape array 2D -  [[0 1 2]
 [3 4 5]]
Original array 1D -  [0 1 2 3 4 5]


In [37]:
# resize()

b = np.arange(6)
print("Original array 1D - ", b)

b.resize(2, 3)
print("Resize array 2D - ", b)
# same array changes permanantly

Original array 1D -  [0 1 2 3 4 5]
Resize array 2D -  [[0 1 2]
 [3 4 5]]


**Assignment**
1. Add a number in 1D array
2. Add a row in 2D array
3. Add a column in 2D array
4. Remove a number from 1D array
5. Remove a row from 2D array
6. Remove a column from 2D array
7. Concatenate 2 arrays

In [38]:
import numpy as np

1. Add a number in 1D array  (add a number to every element of a 1D array)

In [68]:
a = np.arange(5)          # a = np.arange(1,5)  start and stop both values for 1-D
print("Original array - ", a)

addition = a + 5
print("O/P -", addition)


Original array -  [0 1 2 3 4]
O/P - [5 6 7 8 9]


In [69]:
b = np.arange(5)

add_element = np.insert(b, 5, 10)

print(add_element)

[ 0  1  2  3  4 10]


2. Add a row in 2D array

In [70]:
c = np.array([
    [1, 2, 3],
    [4, 5, 6]])

row = [7, 8, 9]
new_arr = np.vstack((c, row))

print(new_arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


3. Add a column in 2D array

In [71]:
d = np.array([
    [1, 2, 3],
    [4, 5, 6]])

col = np.array([
    [7],
    [8] ])

e = np.hstack((d, col))   # adding column
print(e)

[[1 2 3 7]
 [4 5 6 8]]


4. Remove a number from 1D array

In [72]:
f = np.arange(6)
print("Original array - ", f)

f = np.delete(f, 3)       # delete value at index=3
print("O/P - ", f)

Original array -  [0 1 2 3 4 5]
O/P -  [0 1 2 4 5]


In [75]:
g = np.array([10, 20, 30, 40, 50])
print("Original array - ", g)

g = g[g != 40]
print("O/P - ", g)

Original array -  [10 20 30 40 50]
O/P -  [10 20 30 50]


5. Remove a row from 2D array

In [78]:
h  = np.array([
    [1, 2, 3],
    [4, 5, 6]])
print("Original array - ", h)
h = np.delete(h, 1, axis=0)    # 1 = row index (row index starts with 0,1,2...) axis = 0 for row
print("O/P -", h)

Original array -  [[1 2 3]
 [4 5 6]]
O/P - [[1 2 3]]


6. Remove a column from 2D array

In [80]:
i  = np.array([
    [1, 2, 3],
    [4, 5, 6]])
print("Original array - ", i)
i = np.delete(i, 1, axis=1)    # 1 = column index (col index starts with 0,1,2...) axis = 1 for column
print("O/P -", i)

Original array -  [[1 2 3]
 [4 5 6]]
O/P - [[1 3]
 [4 6]]


7. Concatenate 2 arrays

In [81]:
# 1-D
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

s = np.concatenate((arr1, arr2))

print(s)

[1 2 3 4 5 6]


In [82]:
# 2-D

arr1 = np.array([
    [1, 2],
    [3, 4]
])

arr2 = np.array([
    [5, 6],
    [7, 8]
])

r = np.concatenate((arr1, arr2), axis=0)   # axis=0 row wise

print(r)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [86]:
n = np.array([
    [1, 2],
    [3, 4]
])

m = np.array([
    [5, 6],
    [7, 8]
])
t = np.concatenate((arr1, arr2), axis=1)    # axis=1 column wise
print(t)

[[1 2 5 6]
 [3 4 7 8]]


8. Transpose array - row to col/ col to row

In [88]:
u = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])
print("Original Array " , u)

print("Transpose Array ", u.transpose())


Original Array  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose Array  [[1 4 7]
 [2 5 8]
 [3 6 9]]
