**Assignment - Numpy**
1. Create 4x4 array of all True values
2. Create 4x4 array of all False values
3. Create 4x4 array of Digonal elements as 1's and Non diagonal elements as 0's
4. Create 4x4 array of Digonal elements as True and Non diagonal elements as False
5. Create 4x4 array of Digonal elements as False and Non diagonal elements as True

In [1]:
import numpy as np

1.Create 4x4 array of all True values

In [2]:
a = np.full((4,4),'True')   # using shape and fill value
a

array([['True', 'True', 'True', 'True'],
       ['True', 'True', 'True', 'True'],
       ['True', 'True', 'True', 'True'],
       ['True', 'True', 'True', 'True']], dtype='<U4')

In [6]:
# using ones as true
b = np.ones((4, 4), dtype=bool)
b

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

2.Create 4x4 array of all False values

In [7]:
c = np.full((4,4),'False')   # using shape and fill value
c

array([['False', 'False', 'False', 'False'],
       ['False', 'False', 'False', 'False'],
       ['False', 'False', 'False', 'False'],
       ['False', 'False', 'False', 'False']], dtype='<U5')

In [8]:
# using zeros as false
d = np.zeros((4, 4), dtype=bool)
d

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

3.Create 4x4 array of Digonal elements as 1's and Non diagonal elements as 0's

In [18]:
e = np.eye(4,dtype=int)          # 4 consider as row and column as not mentioned different values
                                 # and index = default 0

#e = np.eye(4,4,0,dtype=int)     # row,column,digonal index = default 0
e

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

4.Create 4x4 array of Digonal elements as True and Non diagonal elements as False

In [19]:
f = np.eye(4,dtype=bool)          # 4 consider as row and column and index =default 0
#f = np.eye(4,4,0,dtype=bool)      # row,column,digonal index =default 0
f


array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

5.Create 4x4 array of Digonal elements as False and Non diagonal elements as True

In [20]:
f = ~np.eye(4,dtype=bool)      # row,column,digonal index =default 0
#f = ~np.eye(4,4,0,dtype=bool)      # row,column,digonal index =default 0
f


array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [24]:
g = ~np.eye(5,dtype=bool)
g

array([[False,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True,  True,  True, False]])